version: "3.7"

services:
  web-server:
    build:
      context: .
      dockerfile: ./ts/Dockerfile.dev
    container_name: example-web-server
    volumes:
      - ./ts/src:/home/node/app/src
      - ./ts:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    command: npm start