version: "3.7"

services:
  web-server:
    build:
      context: .
      dockerfile: ./ts/Dockerfile.dev
    container_name: example-web-server
    volumes:
      - ./ts/src:/home/node/app/src
      - ./ts:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    command: npm start

  db-incremental:
    image: postgres:11.5
    container_name: pg_dbt_incremental
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password